### ISSUE TITLE
Build instructions for x86_64/x64

### ISSUE THREAD

**Issue by bil-ash** [Samsung/node-jerryscript#30]
* **Version**:master branch of this repo
* **Platform**:linux(ubuntu) v16.04 (arch x64)
* **Subsystem**:

I built node-jerryscript on my system by turning off the system allocator flag(because that's not supported on 64-bit systems). Although the build was successfull, running any program lead to the error **Segmentation fault. Core dumped**. For a simple console.log the output was displayed and then the error whereas for a simple http server(without any external framework), the error occured before the server could start.
So please provide the build instructions for x86_64/x64 linux.

**Comment by galpeter** [comment]
Hi!

Thanks for reporting! At this moment the main focus is the 32 bit support (that is why there was no instruction on how to build for 64 bit). Still I've created a PR (#31) which should add the required modification to build for 64 bit and execute simple things.

**Comment by bil-ash** [comment]
Thanks.
Seems the  PR #31  has been approved and is about to be merged. I shall try building and running after the merge and report the results here. Till then let the issue remain open.

**Comment by bil-ash** [comment]
I was successfully able to build for x86_64 after the PR.

Some of the simple programs worked but I was not able to start a simple http server. So I tried running the following-
`var http = require('http');

var requestListener = function (req, res) {
  res.writeHead(200);
  res.end('Hello, World!\n');
}

var server = http.createServer(requestListener);
console.log(server);
server.listen(8080);`
and found that there are differences between the output of node installed on my system(v10.x) and node-jerryscript (pic attached)
![Annotation 2019-12-06 115700](https://user-images.githubusercontent.com/33216854/70301887-a174df80-1821-11ea-83b9-4b462f25018d.png)
. Notably **request** and **connection** properties of **_events** object is undefined in node-jerryscript.

Nevertheless my issue was regarding build instructions and I also understand that the project has started only some months ago and it will take some more months for node-jerryscript to be completely usable. So I am closing the issue
